config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?
    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do

  get 'users/index'
  namespace :admin do
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    root to: 'dashboard#index'
  end

  # write your routes here
  resources :users do
    resources:rides, only: %i[new create edit update destroy] 
  end

  resources :rides, only: %i[show index] 
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  #mount ActionCable.server => '/cable'
  root to: 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
    has_many :rides, dependent: :destroy
    accepts_nested_attributes_for :rides
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @rides = Ride.all
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end 
end

app/views/users/show.html.slim
- content_for :title do
  = @user.name

.container
  .row
    aside.col-md-4
      section.user-info
        h2
          'user profile of
        h1 
          =< @user.name

  .row
    .col-mr-4
      - if @user==current_user
        = link_to "Offer a ride", new_user_ride_path(@user.id, @ride), class: "btn btn-primary btn-lg"
      br
    .col
      = link_to "View all rides", rides_path, class: "btn btn-primary btn-lg"
      br
  .row.mt-4
    .col-md-6
      h2 Offered Rides
      br
      = render @user.rides
    .col-md-6
      h2 Joined Rides
      br
      - @rides.each do |ride|
        - if ride.passengers&.include? @user.id
          = render ride