config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?
    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do

  get 'users/index'
  namespace :admin do
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    root to: 'dashboard#index'
  end

  # write your routes here
  resources :users do
    resources:rides, only: %i[new create edit update destroy] 
  end

  resources :rides, only: %i[show index] 
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  #mount ActionCable.server => '/cable'
  root to: 'home#index'
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user

  validates :city_from, presence: true, length: { in: 2..60 }
  validates :city_to, presence: true, length: { in: 2..60 }
  validates :date, presence: true
  validate :date_of_ride_cannot_be_in_the_past
  validates :max_passengers, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 10 }

  private
    def date_of_ride_cannot_be_in_the_past
      if date.present? && date < Date.today
        errors.add(:date, "can't be in the past")
      end
    end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
    def new
        @user = User.find(params[:user_id])
        @ride = @user.rides.build
    end

    def create
        @user = User.find(params[:user_id])
        @ride = @user.rides.create(ride_params)

        if @ride.valid?
            @ride.save
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def destroy
        @user = User.find(params[:user_id])
        @ride = @user.rides.find(params[:id])
        @ride.destroy

        redirect_to user_path(@user)
    end

    def edit
        @ride = Ride.find(params[:id])
        @user = @ride.user
    end

    def update
        @ride = Ride.find(params[:id])
        @user = @ride.user
        @ride.passengers = ride_update(@ride)
        if @ride.update(ride_params)
            redirect_to current_user
        else
            render :edit
        end
    end
    
    def index
        @rides = Ride.all
    end

    def show
        @ride = Ride.find(params[:id])
    end

    private
    def ride_params
        params.require(:ride).permit(:city_from, :city_to, :date, :time, :max_passengers, {:passengers => []})
    end
end

app/helpers/rides_helper.rb
module RidesHelper
    def ride_update(ride)
        if current_user==ride.user
            ride.passengers=ride.passengers
        else
            if ride.passengers&.include? current_user.id
                ride.passengers.delete current_user.id
                ride.passengers=ride.passengers
            else
                if ride.passengers.nil?
                    ride.passengers = Array.new
                end
                if ride.passengers.size < ride.max_passengers
                    ride.passengers=ride.passengers.push current_user.id
                else
                    ride.passengers=ride.passengers
                end
            end
        end
    end
end

app/views/rides/_form.html.slim
= form_with(model: [@user, @ride], local: true) do |form|
  - if @ride&.errors&.any?
    #error_explanation
      h3
        => pluralize(@ride.errors.count, "error")
        | prohibited this ride from being saved:
        ul
          - @ride.errors.full_messages.each do |msg|
            li= msg
  p
    = form.label :city_from, "From"
    br
    = form.text_field :city_from
  p
    = form.label :city_to, "To"
    br
    = form.text_field :city_to
  p
    = form.label :date, "Date"
    br
    = form.date_field :date
  p
    = form.label :Time, "Time"
    br
    = form.time_field :time
  p
    = form.label :max_passengers, "Maximal number of passengers"
    br
    = form.text_field :max_passengers
  p
    = form.submit

app/views/rides/_form_passenger.html.slim
.container
  .d-flex.flex-row
    p
      'From
      strong => @ride.city_from 
      'to
      strong => @ride.city_to 
      'at
      strong => @ride.date.strftime("%d.%m.%Y")
  .d-flex.flex-row
    .p-2
      = form_with(model: [@user, @ride], local: true) do |form|
        = form.hidden_field :city_from
        = form.hidden_field :city_to
        = form.hidden_field :date
        = form.hidden_field :time
        = form.hidden_field :max_passengers
        = form.submit "Yes", class: "btn btn-success btn-lg"
    .p-2
      = link_to "No",  current_user, \
        class: "btn btn-danger btn-lg"

app/views/rides/_ride.html.slim
- if ride.valid?
  .card style="width: 32rem"
    .card-header
      .d-flex.bd-highlight
        .p-2.flex-grow-1.bd-highlight
          'From
          strong => ride.city_from 
          'to
          strong => ride.city_to 
        - if current_user==ride.user
          .p-2.bd-highlight
            = link_to "Edit", edit_user_ride_path(ride.user, ride), \
              class: "btn btn-warning btn-sm"
          .p-2.bd-highlight
            = link_to "Delete", user_ride_path(ride.user, ride), \
              class: "btn btn-danger btn-sm", \
              method: :delete, \
              data: { confirm: "Are you sure?" }
    .card-body
      .container
        .row
          .col
            p 
              'Driver: 
              => ride.user.name   
        .row
          .col
            p 
              'Date: 
              => ride.date.strftime("%d.%m.%Y")
          .col
            p
              'Maximal passengers:
              => ride.max_passengers
        .row
          .col
            p 
              'Time:
              - if ride.time.nil?
                'not available
              - else
                => ride.time.strftime("%H:%M")
          .col
            p 
              'Current passengers:
              - if ride.passengers.nil?
                '0
              - else
                => ride.passengers.size
        .row
          - if current_user!=ride.user
            - if ride[:passengers]&.include? current_user.id
                .d-flex.flex-row
                  .p-2
                    h4 You are registered.
                  .p-2
                    = link_to "Cancel ride?",  edit_user_ride_path(ride.user, ride), \
                      class: "btn btn-outline-danger btn-sm"
            - else
              .row
                .col
                  = link_to "Join",  edit_user_ride_path(ride.user, ride), \
                    class: "btn btn-outline-success btn-lg"
  br

app/views/rides/edit.html.slim
- if current_user==@ride.user
  h1 Edit a ride
  = render "form" 
- else
  - if @ride.passengers&.include? current_user.id
    h1 Cancel ride?
    = render "form_passenger"
  - else
    -if !@ride.passengers.nil? && @ride.passengers.size == @ride.max_passengers
      h1 Sorry, ride is already complete.
      = link_to "Back",  current_user, \
        class: "btn btn-danger btn-lg"
    -else
      h1 Join ride?
      = render "form_passenger"

app/views/rides/index.html.slim
.container
  h1 All rides
  = render @rides

app/views/rides/new.html.slim
h1 Offer a ride
= render "form"

app/views/rides/show.html.slim
= render @ride